### ISSUE TITLE
acesa ou apagada

### ISSUE THREAD

**Issue by Apolinar1o** [Apolinar1o/Lampada#1]
OLá Filho,

Seguinte estou lhe enviando em anexo 1 (um) arquivo em anexo que contém uma pasta com as imagens e um print do PDF para você ver o layout.

O programa tem um conteúdo que precisa ser digitado e formatado. A sua execução trata-se de dois botões :

1 - Ao iniciar o programa a lâmpada precisa vir na imagem desligado (sem  cor);
2 - Ao pressionar o botão ligar troca-se a imagem para ligado ( imagem colorida)
3 - Ao pressionar o botão desligar troca-se a imagem para desligado (sem cor)
@cgonzaga2022

**Comment by cgonzaga2022** [comment]
@Apolinar1o 
Desafio completo com sucesso... apenas 2 (dois) comentários:
1- A versão da língua está em en (Inglês) - para páginas em português do Brasil ajustar para pt-BR
2 - O nome do script é sempre recomendável um nome global e nunca sendo categorizado com o nome de uma ação, sendo assim, deixar por exemplo com script.js
